# Use golang base image
FROM golang:1.21-alpine AS build

# Set the working directory
WORKDIR /app

# Copy the Go modules files
COPY go.mod go.sum ./

# Download and cache Go modules
RUN go mod download

# Copy the source code into the container
COPY . .

# Build the Go app
RUN CGO_ENABLED=0 go build -o /app/webserver .

# Use scratch (empty) base image
FROM scratch

# Copy the built executable from the previous stage
COPY --from=build /app/webserver /webserver

# Command to run the executable
ENTRYPOINT ["/webserver"]

