FROM golang:1.21-alpine AS build
WORKDIR /src/
COPY mongo.go /src/
RUN go mod init github.com/adn02/cloudnativecourse
RUN go mod tidy
RUN CGO_ENABLED=0 go build -o /bin/mongo
FROM scratch
COPY --from=build /bin/mongo /bin/mongo
ENTRYPOINT ["/bin/mongo"]
